### ISSUE TITLE
Exception while downloading state

### ISSUE THREAD

**Issue by SpectralMemories** [rcpoison/dxvk-cache-pool#21]
I have not really investigated any further, but here is the full log:

```
[alex@alex-PC]:~$ dxvk-cache-client 
target directory is: /home/alex/.cache/dxvk-cache-pool
scanning directories
 -> scanned 6 files
preparing wine prefixes
looking up remote base names for 5 possible games
 -> found 4 matching base names
writing 0 new caches
updating 4 caches
 -> HeroesOfTheStorm_x64: is up to date (541 entries)
 -> Diablo III64: is up to date (729 entries)
 -> Overwatch: is up to date (126909 entries)
Feb 01, 2019 3:51:26 PM com.ignorelist.kassandra.dxvk.cache.pool.common.StateCacheIO parse
WARNING: unknown version encountered: 3
 -> Battle.net: signing 98 locally built entries
 -> Battle.net: sending 98 locally built entries to remote
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1077)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:948)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:787)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:785)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:467)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:363)
	at com.ignorelist.kassandra.dxvk.cache.pool.client.rest.CachePoolRestClient.getMissingEntriesSigned(CachePoolRestClient.java:191)
	at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolMerger.mergeExisting(CachePoolMerger.java:304)
	at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolMerger.merge(CachePoolMerger.java:212)
	at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolClient.main(CachePoolClient.java:120)
	... 8 more
```

**Comment by rcpoison** [comment]
Yeah, that's the sanity check preventing uploading garbage.
The state cache format has changed with dxvk-0.96.

**Comment by SpectralMemories** [comment]
I see. I'm guessing it will be fixed soon

**Comment by odysseywestra** [comment]
So in the meantime, which version of dxvk should we be using then?

**Comment by odysseywestra** [comment]
Do you plan on updating this to support the new format for the cache files?
