### ISSUE TITLE
Exception when uploading larger cache files

### ISSUE THREAD

**Issue by Sporif** [rcpoison/dxvk-cache-pool#8]
I'm using the latest from the develop branch.

My Overwatch cache is 53.1MB and contains 30522 entries. BF1 is 39.6MB and contains 22757 entries. Both fail at the upload step.

This was the ouput from the first run.

```
$ dxvk-cache-client --cache-target-dir ~/dxvk-state-cache
target directory is: /home/sporif/dxvk-state-cache
generating key pair: /home/sporif/.config/dxvk-cache-pool
scanning directories
 -> scanned 9 files
preparing wine prefixes
looking up remote caches for 8 possible games
 -> found 5 matching caches
writing 0 new caches
updating 5 caches
 -> Origin: couldn't find reference cache, assuming generated locally
 -> Origin: signing 7 locally built entries
 -> Origin: sending 7 locally built entries to remote
 -> Origin: is up to date (7 entries)
 -> witcher3: couldn't find reference cache, assuming generated locally
 -> witcher3: signing 1176 locally built entries
 -> witcher3: sending 1176 locally built entries to remote
 -> witcher3: is up to date (1176 entries)
 -> Battle.net: couldn't find reference cache, assuming generated locally
 -> Battle.net: signing 26 locally built entries
 -> Battle.net: sending 26 locally built entries to remote
 -> Battle.net: is up to date (26 entries)
 -> Overwatch: couldn't find reference cache, assuming generated locally
 -> Overwatch: signing 30522 locally built entries
 -> Overwatch: sending 30522 locally built entries to remote
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
        at com.ignorelist.kassandra.dxvk.cache.pool.client.rest.CachePoolRestClient.storeSigned(CachePoolRestClient.java:199)
        at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolClient.mergeExisting(CachePoolClient.java:372)
        at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolClient.merge(CachePoolClient.java:287)
        at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolClient.main(CachePoolClient.java:172)
        ... 8 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:390)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
        ... 21 more

```
I remove Overwatch from the folder and it fails at BF1.

```
$ dxvk-cache-client --cache-target-dir ~/dxvk-state-cache
target directory is: /home/sporif/dxvk-state-cache
scanning directories
 -> scanned 8 files
preparing wine prefixes
looking up remote caches for 7 possible games
 -> found 4 matching caches
writing 0 new caches
updating 4 caches
 -> Origin: is up to date (7 entries)
 -> witcher3: is up to date (1176 entries)
 -> Battle.net: is up to date (26 entries)
 -> bf1: couldn't find reference cache, assuming generated locally
 -> bf1: signing 22757 locally built entries
 -> bf1: sending 22757 locally built entries to remote
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
        at com.ignorelist.kassandra.dxvk.cache.pool.client.rest.CachePoolRestClient.storeSigned(CachePoolRestClient.java:199)
        at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolClient.mergeExisting(CachePoolClient.java:372)
        at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolClient.merge(CachePoolClient.java:287)
        at com.ignorelist.kassandra.dxvk.cache.pool.client.CachePoolClient.main(CachePoolClient.java:172)
        ... 8 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:390)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
        ... 21 more

```

I remove BF1 as well and it succeeds with the rest

```
$ dxvk-cache-client --cache-target-dir ~/dxvk-state-cache
target directory is: /home/sporif/dxvk-state-cache
scanning directories
 -> scanned 7 files
preparing wine prefixes
looking up remote caches for 6 possible games
 -> found 3 matching caches
writing 0 new caches
updating 3 caches
 -> Origin: is up to date (7 entries)
 -> witcher3: is up to date (1176 entries)
 -> Battle.net: is up to date (26 entries)
found 3 candidates for upload
 -> ACU: signing
 -> ACU: uploading
 -> bf4: signing
 -> bf4: uploading
 -> UplayService: signing
 -> UplayService: uploading
$ dxvk-cache-client --cache-target-dir ~/dxvk-state-cache
target directory is: /home/sporif/dxvk-state-cache
scanning directories
 -> scanned 7 files
preparing wine prefixes
looking up remote caches for 6 possible games
 -> found 6 matching caches
writing 0 new caches
updating 6 caches
 -> Origin: is up to date (7 entries)
 -> witcher3: is up to date (1176 entries)
 -> ACU: is up to date (694 entries)
 -> UplayService: is up to date (0 entries)
 -> Battle.net: is up to date (26 entries)
 -> bf4: is up to date (5878 entries)
found 0 candidates for upload
```

**Comment by Sporif** [comment]
Here is my dxvk-state-cache folder if it helps.

[dxvk-state-cache.tar.gz](https://github.com/rcpoison/dxvk-cache-pool/files/2457190/dxvk-state-cache.tar.gz)

**Comment by rcpoison** [comment]
@Sporif : oops :(
My ARM server is too slow with signature verification.
I've increased the client read timeout in develop, 
could you please try if that works for you?

**Comment by rcpoison** [comment]
OK, I've rented a VPS.
You can use `--host http://173.212.215.164:16969`, I'll tag a new release with the new server as default later today.

**Comment by rcpoison** [comment]
Client is now pointing to VPS by default, should be fine now.

**Comment by Sporif** [comment]
Yep works fine now.
